# 应用端口
server:
  port: 7901
  servlet:
    context-path:
spring:
  application:
    # 应用名称
    name: provider-user


# eureka 配置  将provider1 注册到eureka的地址 服务名称和服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
  instance:
    instance-id: jcloud-provider3 #修改Eureka上的默认描述信息
logging:
  level:
    root: INFO
